Models/CauThu.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauThu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CauThu()
        {
            this.BanThangs = new HashSet<BanThang>();
        }
    
        public string MaCT { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string TenCT { get; set; }
        public string ViTri { get; set; }
        public int SoAo { get; set; }
        public string CanNang { get; set; }
        public string Images { get; set; }
        public string MaDoi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BanThang> BanThangs { get; set; }
        public virtual DoiBong DoiBong { get; set; }
    }
}

Controllers/CauThuController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using doan.Models;

namespace doan.Controllers
{
    public class CauThuController : Controller
    {
        QLGIAIBONGDAEntities1 database = new QLGIAIBONGDAEntities1();
        public ActionResult DanhSach(string searchValue)
        {
            var cauthu = from a in database.CAUTHU
                           select a;

            if (!String.IsNullOrEmpty(searchValue))
            {
                cauthu = cauthu.Where(s => s.TenCT.Contains(searchValue));
            }
            return View(database.CAUTHU.ToList());
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CAUTHU cauthu, HttpPostedFileBase upload)
        {
            try
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    string uploadDir = "~/UploadedImages/";
                    string uploadPath = Server.MapPath(uploadDir);

                    if (!Directory.Exists(uploadPath))
                    {
                        Directory.CreateDirectory(uploadPath);
                    }

                    string fileName = Path.GetFileName(upload.FileName);
                    string path = Path.Combine(uploadPath, fileName);
                    upload.SaveAs(path);
                    cauthu.Images = uploadDir + fileName;
                }

                if (ModelState.IsValid)
                {
                    database.CAUTHU.Add(cauthu);
                    database.SaveChanges();
                    return RedirectToAction("DanhSach");
                }
            }
            catch (DbEntityValidationException ex)
            {
                foreach (var validationErrors in ex.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        ModelState.AddModelError(validationError.PropertyName, validationError.ErrorMessage);
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error: " + ex.Message);
            }

            return View(cauthu);
        }
        public ActionResult Cauthu()
        {
            return View(database.CAUTHU.ToList());
        }

        public ActionResult Edit(string mact)
        {
            if (string.IsNullOrEmpty(mact))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            CAUTHU cauthu = database.CAUTHU.FirstOrDefault(s => s.MaCT == mact);

            if (cauthu == null)
            {
                return HttpNotFound();
            }

            return View(cauthu);
        }

     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CAUTHU cauthu,string mact, HttpPostedFileBase upload)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        string uploadDir = "~/UploadedImages/";
                        string uploadPath = Server.MapPath(uploadDir);

                        if (!Directory.Exists(uploadPath))
                        {
                            Directory.CreateDirectory(uploadPath);
                        }

                        string fileName = Path.GetFileName(upload.FileName);
                        string path = Path.Combine(uploadPath, fileName);
                        upload.SaveAs(path);
                        cauthu.Images = uploadDir + fileName;
                    }

                    database.Entry(cauthu).State = EntityState.Modified;
                    database.SaveChanges();
                    return RedirectToAction("DanhSach");
                }
            }
            catch (DbEntityValidationException ex)
            {
                foreach (var validationErrors in ex.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        ModelState.AddModelError(validationError.PropertyName, validationError.ErrorMessage);
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error: " + ex.Message);
            }

            return View(cauthu);
        }
        public ActionResult Delete(string mact)
        {
            var cauthu = database.CAUTHU.FirstOrDefault(s => s.MaCT == mact);

            if (cauthu == null)
            {
                return HttpNotFound();
            }

            return View(cauthu);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string mact)
        {
            var cauthu = database.CAUTHU.FirstOrDefault(s => s.MaCT == mact);

            if (cauthu != null)
            {
                database.CAUTHU.Remove(cauthu);
                database.SaveChanges();
            }

            return RedirectToAction("DanhSach");
        }

    }
}

Views/CauThu/Cauthu.cshtml
@model  IEnumerable<doan.Models.CAUTHU>

@{
    ViewBag.Title = "Cauthu";
    Layout = "~/Views/Shared/_Nen.cshtml";
}


<h2 style="text-align:center">Cauthu</h2>
<div class="container-fluid">   
    <div class="row">
        @foreach(var item in Model)
                {
             <div class="col-sm-6 col-md-4 col-lg-3"
                  <div class="div-img-client">
                      <img src="@Url.Content(item.Images) " height="150" width="150"
                  </div>
                  <div class="div-des-client">
                      <p>@Html.DisplayFor(model => item.MaCT)</p>
                      <p>@Html.DisplayFor(model => item.TenCT)</p>
                      <p>@Html.DisplayFor(model => item.ViTri)</p>
                  </div>
        }
    </div>

</div>

Views/CauThu/Create.cshtml
@model doan.Models.CAUTHU

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_QuanLy.cshtml";
}

<style>
    .huy {
        background-image: linear-gradient(120deg, #d4fc79 0%, #96e6a1 100%);
    }
    .h2 {
        text-align: center;
        color: purple;
        font-size: 30px;
    }

    .h4 {
        text-align: center;
        color: purple;
    }

    .form-horizontal {
        background-image: url('https://noithatbinhminh.com.vn/wp-content/uploads/2023/09/background-bong-da-03.jpg');
    }

    .form-group {
        font-weight: bold;
        justify-content: center; 
        align-items: center; 
    }
    .buton {
        background: linear-gradient(to right, #ff7eb3, #ff65a3, #7a77ff, #86a8e7); /* Gradient màu */
        border: none;
        border-radius: 50px; /* Làm bo tròn các góc của nút */
        color: white;
        padding: 10px 20px; /* Khoảng cách bên trong nút */
        font-size: 16px;
        font-weight: bold;
        text-align: center;
        text-decoration: none;
        transition: background 0.3s ease;
        cursor: pointer;
        display: inline-block;
        margin: 5px;
    }

        .buton:hover {
            background: linear-gradient(to right, #ff65a3, #ff7eb3, #86a8e7, #7a77ff);
        }
</style>

<div class="huy">
    @using (Html.BeginForm("Create", "CauThu", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()



        <div class="form-horizontal">
            <h2 class="h2">Thêm cầu thủ</h2>
            <h4 class="h4">CauThu</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.MaCT, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MaCT, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MaCT, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TenCT, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TenCT, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenCT, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ViTri, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ViTri, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ViTri, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SoAo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SoAo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SoAo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CanNang, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CanNang, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CanNang, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MaDoi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MaDoi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MaDoi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label for="upload" class="control-label col-md-2">Upload Image</label>
                <div class="col-md-10">
                    <input type="file" name="upload" id="upload" />
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "DanhSach",null, new { @class = "buton" })
    </div>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        <script type="text/javascript">
            function ChangeImage(input, previewElement) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        previewElement.src = e.target.result;
                        previewElement.style.display = 'block';
                    };
                    reader.readAsDataURL(input.files[0]);
                }
            }
        </script>
    }
</div>

Views/CauThu/DanhSach.cshtml
@model IEnumerable<doan.Models.CAUTHU>
@{ ViewBag.Title = "DanhSach";
    Layout = "~/Views/Shared/_Danhsach.cshtml";
}
<style>
    .1 {
        font-size: 30px;
        padding: 20px;
        background: rgba(255, 255, 255, 0.8);
    }
    .text-container {
        display: flex;
    }

    .text-box {

        border: 5px solid #4CAF50; 
        padding: 20px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        background-color: #ffffff;
        text-align: left;
        font-size: 24px; 
        color: #333; 
        max-width: 90%;
        margin: auto;
    }
    .table th {
        color: #4CAF50;
        font-weight: bold; 
        font-size: 30px;
    }
    .table td {
        color:whitesmoke;
        font-weight: bold;
        font-size: 20px;
    }
    .btn btn-warnin {
        background: linear-gradient(to right, #ff7eb3, #ff65a3, #7a77ff, #86a8e7); 
        border: none;
        border-radius: 50px; 
        color: white;
        padding: 10px 20px; 
        font-size: 16px;
        font-weight: bold;
        text-align: center;
        text-decoration: none;
        transition: background 0.3s ease; 
        cursor: pointer;
        display: inline-block;
        margin: 5px;
    }
        .btn btn-warnin:hover {
            background: linear-gradient(to right, #ff65a3, #ff7eb3, #86a8e7, #7a77ff); 
        }
    .form-actions.no-color {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 10px; 
    }
    .type {
        display: flex;
        justify-content: center;
        align-items: center;
    }
</style>
<div class="class">
    <div class="text-container">
        <div class="text-box">
            Danh Sách Cầu Thủ
        </div>
    </div>
    <p>
        @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-success" })
    </p>
    <table class="table">
        <div class="type">
            <input type="text" name="searchValue" placeholder="Nhập từ khóa..." />
            <button type="submit">Tìm kiếm</button>
        </div>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MaCT)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NgaySinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TenCT)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ViTri)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoAo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CanNang)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaDoi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Images)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MaCT)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgaySinh)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TenCT)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ViTri)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SoAo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CanNang)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaDoi)
                </td>
                <td>
                    <img src="@Url.Content(item.Images)" alt="Hình ảnh người chơi" style="width:100px; height:auto;" />
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { mact = item.MaCT }, new { @class = "btn btn-success" }) |
                    @Html.ActionLink("Details", "Details", new { mact = item.MaCT }, new { @class = "btn btn-danger" }) |
                    @Html.ActionLink("Delete", "Delete", new { mact = item.MaCT }, new { @class = "btn btn-dark" })
                </td>

            </tr>
        }

    </table>
    <div class="form-actions no-color">
        <a href="/Home/TrangChu" class="btn btn-warning"> Trang chu</a>
        <a href="/CauThu/Cauthu" class="btn btn-warning"> Xem cau thu</a>
    </div>

Views/CauThu/Delete.cshtml
@model doan.Models.CAUTHU

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Nen.cshtml";
}
<style>
    .hi {
    width: 400px;
    background-size: cover;
    padding: 30px;
    align-items: center;
    justify-content: center;
    border-radius: 10px;
    box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);
    position: relative;
}

    .hi:before {
        content: "";
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        
        border-radius: 10px;
    }
    .h1 {
        border: 5px solid #4CAF50; 
        padding: 20px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); 
        background-color: #ffffff; 
        text-align: left; 
        font-size: 24px; 
        color: #333; 
        max-width: 90%; 
        margin: auto;
    }

    .button {
        background: linear-gradient(to right, #ff7eb3, #ff65a3, #7a77ff, #86a8e7); 
        border: none;
        border-radius: 50px; 
        color: white;
        padding: 10px 20px; 
        font-size: 16px;
        font-weight: bold;
        text-align: center;
        text-decoration: none;
        transition: background 0.3s ease; 
        cursor: pointer;
        display: inline-block;
        margin: 5px; 
    }
        .button:hover {
            background: linear-gradient(to right, #ff65a3, #ff7eb3, #86a8e7, #7a77ff); 
        }
    .buton {
        background: linear-gradient(to right, #ff7eb3, #ff65a3, #7a77ff, #86a8e7); 
        border: none;
        border-radius: 50px; 
        color: white;
        padding: 10px 20px; 
        font-size: 16px;
        font-weight: bold;
        text-align: center;
        text-decoration: none;
        transition: background 0.3s ease; 
        cursor: pointer;
        display: inline-block;
        margin: 5px; 
    }
    .buton:hover {
        background: linear-gradient(to right, #ff65a3, #ff7eb3, #86a8e7, #7a77ff); 
    }

    .form-actions.no-color {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 10px; 
    }
</style>
<div class="h1">
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
</div>
<div class="hi">
    <h4>CauThu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaCT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaCT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenCT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenCT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ViTri)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ViTri)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoAo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoAo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CanNang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CanNang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaDoi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaDoi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Images)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Images)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="button" /> |
            @Html.ActionLink("Trở về", "DanhSach",null,new {@class="buton"})
        </div>
    }
</div>

Views/CauThu/Edit.cshtml
@model doan.Models.CAUTHU

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "CauThu", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CauThu</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaCT)

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenCT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenCT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenCT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ViTri, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ViTri, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViTri, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoAo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoAo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoAo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CanNang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CanNang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CanNang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaDoi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaDoi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaDoi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="upload" class="control-label col-md-2">Upload Image</label>
            <div class="col-md-10">
                <input type="file" name="upload" id="upload" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "DanhSach")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}